theme: jekyll-theme-minimal
title: Eugene Mazarakis
description: A simple website using Jekyll's Minimal theme.



#title: Eugene Mazarakis
#logo: /assets/Img/Eugene_Photo.png
logo: /assets/Img/Eugene_Photo_2.png
#description: Data Analyst/Data Enginner
#show_downloads: true 

#theme: jekyll-theme-minimal
