theme: jekyll-theme-minimal
title: My Website
description: A simple website using Jekyll's Minimal theme.

plugins:
  - jekyll-seo-tag

# Include Font Awesome
css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css

